# Generated by Django 3.2.5 on 2021-09-13 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='shares',
        ),
        migrations.DeleteModel(
            name='Share',
        ),
    ]
