# Generated by Django 3.2.5 on 2021-11-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20210914_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
