# Generated by Django 3.2.5 on 2021-08-30 23:54

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='Profile/picture/default.jpg', upload_to=accounts.models.Uplaod_user_image),
        ),
    ]
