# Generated by Django 3.2.5 on 2021-09-14 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_customuser_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourceblock', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targetblock', to=settings.AUTH_USER_MODEL)),
            ],
        ),
         migrations.RemoveField(
            model_name='customuser',
            name='block',
        ),
        migrations.AddField(
            model_name='customuser',
            name='block',
            field=models.ManyToManyField(blank=True, related_name='_accounts_customuser_block_+', through='accounts.Block', to=settings.AUTH_USER_MODEL),
        ),
    ]
