# Generated by Django 3.2.5 on 2021-10-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='action',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
