# Generated by Django 3.2.5 on 2021-10-20 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0002_activity_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser', models.CharField(blank=True, max_length=150, null=True)),
                ('os', models.CharField(blank=True, max_length=150, null=True)),
                ('device', models.CharField(blank=True, max_length=150, null=True)),
                ('is_mobile', models.BooleanField(default=False)),
                ('is_tablet', models.BooleanField(default=False)),
                ('is_pc', models.BooleanField(default=False)),
                ('is_touch_capable', models.BooleanField(default=False)),
                ('is_bot', models.BooleanField(default=False)),
                ('logtime', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserAuthActivity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Auth Log',
                'verbose_name_plural': 'Activities Auth logs',
            },
        ),
    ]
