# Generated by Django 3.2.5 on 2021-10-20 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_authactivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='authactivitylog',
            name='action',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
