# Generated by Django 3.2.5 on 2021-10-20 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_authactivitylog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='authactivitylog',
            name='ipaddress',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
