# Generated by Django 3.2.5 on 2021-11-04 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notification_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
